### ISSUE TITLE
Relative time

### ISSUE THREAD

**Issue by rocketraman** [jacobras/Human-Readable#21]
I have some code that will output human readable relative times e.g.

5 seconds ago

3 minutes ago

In 3 minutes

Etc

Any interest in having this as a contribution to this library? I haven't looked into the sources yet but would love to have all this functionality in one maintained place.

**Comment by jacobras** [comment]
Hi @rocketraman 🙋🏼‍♂️! This library already does exactly that. You can call `HumanReadable.timeAgo(someInstant)` and it will return ```"5 seconds ago"``` (or ```"in 5 seconds"``` for future datetimes).

**Comment by rocketraman** [comment]
Nice, glad to hear that! Sorry for the noise.

**Comment by jacobras** [comment]
No worries, feel free to check out the library if you have a use for it :)
