### ISSUE TITLE
Failed to resolve: nl.jacobras:human-readable:1.7.0

### ISSUE THREAD

**Issue by vinceglb** [jacobras/Human-Readable#29]
I was going to implements this library but gradle failed to resolve the library.

By visiting Sonatype Maven Central, the last release is 1.2.0: 
https://central.sonatype.com/artifact/nl.jacobras/human-readable/versions

Is there anything I'm missing in order to use the latest release (1.7.0)?

**Comment by jacobras** [comment]
Hi @vinceglb , thanks for reporting! It seems when I published 1.7.0, I bumped the version only in the documentation but the commit with the actual version increase wasn't pushed, so it re-published the previous version. I now ran the publication again and it should be available shortly.

About the Sonatype link: it's case-sensitive 😑 At one point I changed the `rootProject`'s name to be capitalized and now there are two links. If you look at https://central.sonatype.com/artifact/nl.jacobras/Human-Readable/versions, you'll find the newer versions (including 1.7.0).

**Comment by vinceglb** [comment]
Thank you for your answer!

I've noticed that the lowercase version is not working:
`implementation("nl.jacobras:human-readable:1.7.0")`

We need to use the capitalized version now:
`implementation("nl.jacobras:Human-Readable:1.7.0")`

But it's working 👌

**Comment by jacobras** [comment]
That's crazy. Thanks for reporting back, I updated the readme.
