### ISSUE TITLE
Polish: date for single hour/minute/... uses incorrect form

### ISSUE THREAD

**Issue by krzema12** [jacobras/Human-Readable#42]
E.g.:
* "za 1 minuta" -> should be "za 1 minut**ę**"
* "za 1 godzina" -> should be "za 1 godzin**ę**"
* "1 godzina temu" -> should be "1 godzinę temu"

**Comment by jacobras** [comment]
Thanks for reporting! It's also incorrect for German and Russian.

Consolidating this into #47.
