### ISSUE TITLE
Incorrect Czech localization for "%d ${time} ago" case

### ISSUE THREAD

**Issue by jakubturcovsky** [jacobras/Human-Readable#93]
The Czech language has inflection differences based on prepositions. Standalone localization of 5 days is `5 dní`, but it changes with a preposition for the past (the future is the same as without a preposition): 5 days ago: `před 5 dny`.

The whole sample is:
**Days**
`před 0 dny`
`před 1 dnem`
`před 2-∞ dny`

The same goes for other time units:
**Minutes**
`před 0 minutami`
`před 1 minutou`
`před 2-∞ minutami`

**Seconds**
`před 0 sekundami`
`před 1 sekundou`
`před 2-∞ sekundami`

etc.

I can provide a full translation (or check PR) if needed.

**Comment by jacobras** [comment]
Hi @jakubturcovsky, thanks for reporting! I missed this in #83. Thanks for providing the examples, I'll fix it in the next version 1.10.0.

**Comment by jacobras** [comment]
@jakubturcovsky I opened a PR, would be much appreciated if you could take a look!
